[build]
  base = "frontend"  # Diret칩rio base onde est치 o package.json
  command = "npm run build"
  publish = "frontend/build"  # Diret칩rio onde o build ser치 gerado

[[redirects]]
  from = "/speedtest"
  to = "http://localhost:5000/speedtest"
  status = 200
